[pytest]
# Указываем, где искать тесты
testpaths = tests
# Какие файлы считать тестовыми
python_files = test_*.py
# Какие функции считать тестами
python_functions = test_*
# Добавляем стандартные аргументы (например, всегда показывать отчет)
addopts = -v 